sudo: required
dist: precise
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'gcov-4.6']
      env: COMPILER=g++-4.8
    - os: linux
      compiler: clang
      env: COMPILER=clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcov-4.6']

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq cmake doxygen lcov
  
before_script:
  - gcov --version | grep gcov
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=On -DCMAKE_CXX_COMPILER=$COMPILER ..

script:
  - make -j3
  - make test
  - make draw_test-gcov
  - make lcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
