sudo: required
dist: precise
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8', 'g++-4.8', 'gcov-4.8']
      env: COMPILER=g++-4.8
#    - os: linux
#      compiler: clang
#      env: COMPILER=clang++
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['gcc-4.8', 'gcov-4.8']

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq cmake doxygen lcov
  
before_script:
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
  - uname -a
  - printenv
  - $COMPILER --version
  - cmake --version
  - which gcc && gcc --version
  - which g++ && g++ --version
  - which gcov && gcov --version
  - lcov --version | grep lcov
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=On -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC ..

script:
  - make -j3
  - make test
  - make draw_test-gcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
