sudo: required
dist: precise
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8', 'g++-4.8', 'gcov-4.8']
      env:
        - CXX_COMPILER=g++-4.8
        - C_COMPILER=gcc-4.8
        - Codecove="On"
      before_script:
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
        - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc && gcc --version
        - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++ && g++ --version
        - sudo ln -sf /usr/bin/gcov-4.8 /usr/bin/gcov && gcov --version
      after_success:
        - bash <(curl -s https://codecov.io/bash) -X gcov
    - os: linux
      compiler: clang
      env: 
        - CXX_COMPILER=clang++
        - C_COMPILER=clang
        - Codecove="Off"

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq cmake doxygen
  
before_script:
  - uname -a
  - printenv
  - $CXX_COMPILER --version
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=$Codecove -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER ..
  - make -j3
  - make test
  - if [[ "$Codecove" == "On" ]];  then make draw_test-gcov; fi
