sudo: required
dist: precise
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8
    - os: linux
      compiler: clang
      env: COMPILER=clang++

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq cmake doxygen
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script: make -j4

after_success:
  - bash <(curl -s https://codecov.io/bash)