sudo: required
dist: precise
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8', 'g++-4.8', 'gcov-4.8']
      env: COMPILER=g++-4.8
#    - os: linux
#      compiler: clang
#      env: COMPILER=clang++
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['gcc-4.8', 'gcov-4.8']

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq cmake doxygen
  
before_script:
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
  - uname -a
  - printenv
  - $COMPILER --version
  - cmake --version
  - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc && gcc --version
  - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++ && g++ --version
  - sudo ln -sf /usr/bin/gcov-4.8 /usr/bin/gcov && gcov --version
  - sudo ln -sf /usr/bin/lcov-1.11 /usr/bin/lcov && lcov --version
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=On -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC ..

script:
  - make -j3
  - make test
  - make draw_test-gcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
