language: cpp

compiler:
  - gcc
  - clang
  
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq cmake doxygen
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
