version: "{build}"

branches:
  only:
    - master
    
configuration:
  - Debug
  - Release
  
install:
  - ps: cmake --version
  - ps: msbuild /version
  - ps: (New-Object net.webclient).DownloadFile('http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.8.windows.bin.zip', "$pwd\doxygen-1.8.8.windows.bin.zip")
  - ps: 7z X doxygen-1.8.8.windows.bin.zip -Odoxygen

build_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=Off .. 
  - cmake --build . --config %configuration% --target draw
