version: 0.0.0-{build}

environment:
  matrix:
  - Generator: Visual Studio 14 2015
  - Generator: Visual Studio 12 2013
  - Generator: MinGW Makefiles
  
branches:
  only:
    - master
    
configuration:
  - Debug
  - Release
    
platform:
  - x86

install:
  - ps: cmake --version
  - ps: msbuild /version
  - choco install doxygen.portable

build_script:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -G "%Generator%" -DCMAKE_BUILD_TYPE=%configuration% -DENABLE_COVERAGE=Off .. 
  - cmake --build . --config %configuration%
