
os:
  - Visual Studio 2015
  
branches:
  only:
    - master
    
configuration:
  - Debug
  - Release
    
platform:
  - x86

install:
  - ps: cmake --version
  - ps: msbuild /version
  - choco install doxygen.portable

build_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=Off .. 
  - cmake --build . --config %configuration%
