version: 1.0.{build}

branches:
  only:
    - master

build_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=Off .. 
  - cmake --build . --config Release --target draw
  - cmake --build . --config Debug --target draw
